### ISSUE TITLE
Download subtitle files

### ISSUE THREAD

**Issue by oas777** [opencast/opencast-editor#1007]
The editor already handles WebVTT files (receiving them from Opencast and sending them back). It would be great if users could download them. This would, for example, allow them to edit/process them in professional tools for subtitling. The download button could be part of the subtitle editor view like this:

![Screenshot from 2023-09-27 20-26-52](https://github.com/opencast/opencast-editor/assets/1008395/70967949-7aac-4f86-a783-cb6edf470ad8)

---

EDIT(@lkiesow): I added the missing description for this issue

**Comment by Pavol-Beskid** [comment]
Hi! I am interested in solving this issue, may I get assigned to it?

**Comment by lkiesow** [comment]
Sure. Thanks for taking this on.

**Comment by Prashant04627** [comment]
Hi, can i take this issue and solve it?

**Comment by oas777** [comment]
Looks like @Pavol-Beskid is already assigned. How about https://github.com/opencast/opencast-editor/issues/999#issuecomment-1737895055?

**Comment by Arnei** [comment]
Solved by #1185
