### ISSUE TITLE
Make the timeline "zoomable"

### ISSUE THREAD

**Issue by Arnei** [opencast/opencast-editor#107]
Currently the UI doesn't do too well with handling multiple smaller cuts in a row. Especially on video files with long lengths, this can become a problem. To allow for precise graphical cutting, it would be nice to allow users to "zoom into" the timeline. Typically this would mean looking at only a portion of the timeline, in which the scrubber can then be moved with higher precision than normal.

**Comment by Arnei** [comment]
Pinning this as it is quite far down the issue list, but also arguably the most requested feature we have. Work on this if you want to make a lot of people happy :)

**Comment by dagraf** [comment]
> from my experience I think that this is a must have feature for the foreseeable future - especially if you cut long videos :)

I totally agree.

**Comment by marcusm7** [comment]
> from my experience I think that this is a must have feature for the foreseeable future - especially if you cut long videos :)

Yes. Zoom and maybe direct editing of time codes.
Editing of longer recordings is hard without.
