### ISSUE TITLE
Metadata: Publisher

### ISSUE THREAD

**Issue by oas777** [opencast/opencast-editor#1080]
Not sure whether this is the right place, because I'm coming from Tobira to
https://oc.tobira.ethz.ch/editor-ui/index.html?mediaPackageId=25e82f02-db10-4ba6-937f-3252353cfbe8: The metadata field for "Publisher" has no field, no border, and no option to edit.

**Comment by Arnei** [comment]
Yes, this is the right place. It looks something like this on your end, right?
![Uploading Bildschirmfoto vom 2023-06-21 09-38-51.png…]()

The metadata view in the editor only allows you to edit fields that you could also edit in the Opencast Admin UI. And "Publisher" is one of three fields that are not editable per default in Opencast. Maybe the graphic design in the editor should be more clear that the field is "non-editable" and not straight up broken?

**Comment by oas777** [comment]
Yes, that was probably what I wanted to say. I thought "greyed out" is the design for "non-editable" like "Created" (where the border is missing). The other way round it's good the editor is "protecting" the metadata protected from changes in Opencast.
