### ISSUE TITLE
Add "remove all segments" function

### ISSUE THREAD

**Issue by kweingaertne** [opencast/opencast-editor#1083]
In the old editor, there was a button to remove all the segments automatically made in a given recording. Having this back would be a great quality of life improvement. Also, it would be great to be able to restore or delete segments without moving the cursor into the segment first. In the old editor, there was a little icon on the top right corner of every segment, letting you delete/ restore them without interrupting playback.

**Comment by Arnei** [comment]
Regarding the second part of this issue: I personally dislike the icons in the top right segment corner. They're small and thus hard to hit, they disappear if segments are too small, and are often just as far away from the cursor as the general delete button.  I think keyboard shortcuts are a better solution.

But you mentioned that would like to be able to delete/restore segments without interrupting playback. I had not considered this previously, could you describe your use case in greater detail? I'd be interested in hearing if others have the same use case.

**Comment by dagraf** [comment]
I agree here with @Arnei: I like that we do not have the icons in the top right segment corner anymore. Deleting/restoring segments without interrupting playback is still possible if the option "Preview mode" is DEactivated.

**Comment by ziegenberg** [comment]
If you click "Merge All" Segments, this removes all segments. Which is basically the description of this issue. I would consider this as "solved".

**Comment by dagraf** [comment]
@ziegenberg: I guess your referring tho https://github.com/opencast/opencast-editor/pull/1097? If so, I would consider it as solved, too.

**Comment by Arnei** [comment]
Cool, closing this then. If people want to further discuss the second part of this issue, they may open another issue for that.
