### ISSUE TITLE
Provide return link for integration

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast-editor#1084]
Similar to Studio, it would be nice if a system integrating the Editor could provide a return link to the editor via URL parameter which would then be shown to users when they are finished editing and when they would currently be stuck in a dead end (e.g. after starting the processing):

![27d77d15-215b-44fc-960e-66e008758746](https://github.com/opencast/opencast-editor/assets/1008395/2411e8e1-56e5-4ab1-ac0b-34c8011bb9a3)

Which systems are allowed should be a configuration option in the editor configuration file so that you cannot generate an editor link which at the end will lead you to a malicious site. But this can be a very simple list of URL prefixes like `["https://opencast.org/", "https://university.edu/"]`.

**Comment by dennis531** [comment]
I am not really sure whether the callback url should be an option in the config file. I think this should not be a problem, since URL parameters have a higher priority and the option in the file could be seen as a default value.

On the other hand, the list of allowed domains/prefixes should be configurable only in the file. Otherwise, this mechanism would not provide any protection.

**Comment by dennis531** [comment]
Preview:
![image](https://github.com/opencast/opencast-editor/assets/44410838/c5b27e9b-4404-40d9-8412-9108ff894302)

**Comment by snoesberger** [comment]
This is also an important feature for our institution, as users sometimes need to edit several videos in a row and want to go back to where they started. Or they may simply want to pick up where they left off before they started the editor.


> I think `Back to LMS` is too specific as we don't know if the return link refers to a LMS. I would suggest to name it more generic, e.g. `Back to previous system`.

I agree with that. It would be even better to make the button name configurable. You could specify a name in the config file for each permitted URL or prefix. This name then would be displayed as button text:

"Tobira": "https://tobira.opencast.org" --> Button text = "Back to Tobira"
"ILIAS": "https://ilias.university.edu" --> "Back to ILIAS"

**Comment by ziegenberg** [comment]
@Arnei, I think this can be closed since #1100 was merged.
