### ISSUE TITLE
"Fertigstellen" not part of the navigation to the left?

### ISSUE THREAD

**Issue by oas777** [opencast/opencast-editor#1105]
![grafik](https://github.com/opencast/opencast-editor/assets/1752342/b2a3d81d-aa4c-47d9-b732-68adc3eee6fd)

Is this supposed to indicate "Fertigstellen" is different from others?

**Comment by Arnei** [comment]
Fixed in [c869b41](https://github.com/opencast/opencast-editor/pull/1079/commits/c869b41dcf8f85efe923da63a09b2fcb05b4d75a)

(Test it here: https://test.editor.opencast.org/1079/2023-07-17_14-50-34/)

**Comment by oas777** [comment]
Thanks!
