### ISSUE TITLE
Coherent "language switching" for Tobira, Editor, and Studio

### ISSUE THREAD

**Issue by oas777** [opencast/opencast-editor#1108]
Separating this from the redesign PR and https://github.com/opencast/opencast-editor/pull/1079#issuecomment-1635493091: This should be coherent across the three, ideally a decision made in one should be continued in the other when using Editor or Studio in a Tobira setting.

**Comment by LukasKalbertodt** [comment]
The new Studio design: 

![image](https://github.com/opencast/opencast-editor/assets/7419664/3ce6b2ee-88f3-46a4-8608-d5da648a3d7a)

... will use the exact same UI as Tobira:

![image](https://github.com/opencast/opencast-editor/assets/7419664/7f21da5e-d53c-4197-8034-ff38048b04ba)

(With the only difference that Studio shows the label on wide screens).

This part of the code is already extracted into `appkit` and should be usable relatively easily by the Editor as well. It seems like the Editor would have plenty of space in the header for that.

The same thing applies to the color theme switcher btw, which is also in the header and will look the same for Studio and Tobira.

**Comment by oas777** [comment]
Excellent. Two down, one to go (actually two, if the coherent settings within Tobira are an issue of their own).

**Comment by Arnei** [comment]
> This part of the code is already extracted into appkit and should be usable relatively easily by the Editor as well. It seems like the Editor would have plenty of space in the header for that.

Unfortunately not yet usable by the Editor, so we may have to go with our own solution (or fix appkit to work with the Editor, which is more complicated than expected).

**Comment by LukasKalbertodt** [comment]
For the protocol: we discussed this internally and we are planning on adjusting `appkit` soon (TM) to make it possible for Editor to use the exact same header.

**Comment by lkiesow** [comment]
Additionally, to selecting a specific language, being able to select system language would be really nice. I think that should also be the default.

**Comment by lkiesow** [comment]
> This should be coherent across the three, ideally a decision made in one should be continued in the other when using Editor or Studio in a Tobira setting.

I think you forgot the player? While it could be slightly different there, the overall concept should at least be similar.

**Comment by oas777** [comment]
I did forget the player. The other way round, the (ETHZ) player doesn't support that many languages, cf. https://github.com/polimediaupv/paella-ethz/tree/main/src/i18n. Are you volunteering for a German version?

**Comment by LukasKalbertodt** [comment]
I suppose this can be closed? The only other thing mentioned here is now tracked in #1137

**Comment by oas777** [comment]
Yes. Do you intend to add "Language" in Tobira to the icon?

**Comment by LukasKalbertodt** [comment]
I hadn't planned on it. I know we want coherence, but I think the icon is enough in that case. Tobira has lots more stuff in its header so it doesn't really have space for the labels.

**Comment by oas777** [comment]
> I did forget the player. The other way round, the (ETHZ) player doesn't support that many languages, cf. https://github.com/polimediaupv/paella-ethz/tree/main/src/i18n. Are you volunteering for a German version?

Is there interest in creating a German version for Paella? Interest that results in volunteering? Should I take this to the DACH list?

**Comment by lkiesow** [comment]
If we can get the translation keys to Crowding, getting some translations shouldn't be a problem
https://crowdin.com/profile/opencast
