### ISSUE TITLE
German only: Do not address users as "du".

### ISSUE THREAD

**Issue by dagraf** [opencast/opencast-editor#1129]
Most messages appearing in the editor are written with "Sie" but there is at least one occasion, where users get addresse as "du" (see screenshot: "Bist du sicher, dass..."). Solution: Please get rid of those "du" expressions.
<img width="1256" alt="Bildschirmfoto 2023-08-17 um 16 57 14" src="https://github.com/opencast/opencast-editor/assets/15246287/5aa53d7d-5ba4-4c7c-b013-cb120b44e1ad">

**Comment by mliradelc** [comment]
In Spanish I have the same question. Should the translation in Opencast treat the user in a formal way ("Usted") or more personal ("tú")

**Comment by Arnei** [comment]
No more "Du" in the translation files, should be updated soonish.

If you want to make changes to the translation yourself, you can request to join our crowdin project: https://github.com/opencast/opencast-editor#translating-the-editor. Crowdin allows you to translate in your browser, no coding or github knowledge required.

**Comment by Arnei** [comment]
@mliradelc I think it might be better to discuss your question in a seperate issue? I don't think many people interested in the spanish translation will take a look at an issue titled "German only" :D.
