### ISSUE TITLE
UX/UI: Clarify confusion around "Save changes" vs. "Start processing"

### ISSUE THREAD

**Issue by oas777** [opencast/opencast-editor#1131]
Testing at ETH showed the difference between the two and their specific functionalities are not self-explanatory, despite the description. We would appreciate a discussion around this.

**Comment by oas777** [comment]
#https://github.com/elan-ev/opencast-studio/issues/1061

**Comment by lkiesow** [comment]
Our users ran into the same problem. “Saving” vs “Processing” is really confusing. Especially if you just want to update the metadata. At least that we can hopefully improve once the auto-update of metadata is finished which is under development right now.

**Comment by oas777** [comment]
Can you elaborate on this feature? While I can see it help in certain situation, it will not necessarily solve this UX/UI issue.

**Comment by oas777** [comment]
Needs further discussion, maybe input by designer (Lisa).

**Comment by Arnei** [comment]
Agreed, this totally unintuitive. However, I also find it really difficult to abstract from the Opencast context. A designer input would be greatly appreciated.

**Comment by oas777** [comment]
Cf. https://github.com/elan-ev/opencast-studio/issues/1099 also.

**Comment by lkiesow** [comment]
As a first step, let's overhaul the naming.
@kai-wng-uos, can you describe what we discussed in more detail?

A few notes from our discussion:

- Start processing also saves changes
- Start processing should mention publication instead
- Go through labels and wording in general
