### ISSUE TITLE
Allow users to move existing cutmarks

### ISSUE THREAD

**Issue by oas777** [opencast/opencast-editor#1132]
Together with https://github.com/opencast/opencast-editor/issues/107, this is necessary for precision cuttting.

**Comment by lkiesow** [comment]
Can you elaborate a bit more on what you would like to see?

**Comment by oas777** [comment]
Once you have set cutmarks (or cutmarks were suggested based on audio analysis), this features allows you to move the cutmarks a few frames or seconds (especially when zoomed) to correct them. Which is not possible right now:

![image](https://github.com/opencast/opencast-editor/assets/1752342/10e6d462-fe84-45c1-989c-7f65ddcee1bf)

**Comment by lkiesow** [comment]
Additional/alternative description in #1228
