### ISSUE TITLE
Generating/saving thumbnails does not work

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast-editor#1154]
Generating/saving a thumbnail does not seem to work:

1. Go to [editor.opencast.org](https://editor.opencast.org/?id=ID-goat)
2. Go to “thumbnail”
3. Generate a thumbnail
4. Go to “Finish” → “Save” and save your work
5. Reload the editor
6. The thumbnail is gone

**Comment by Arnei** [comment]
The thumbnail are saved to Opencast at least. Seems like the editor fails to load them because the editor backend gets the thumbnails from the internal publication (to which the thumbnails are not published).

**Comment by lkiesow** [comment]
Since they are quite small, can we get them from the asset manager directly instead? That should be easy enough, shouldn't it?

**Comment by Arnei** [comment]
Related PR in OC merged, meaning this will be fixed starting OC 13.13 and 14.6.
