### ISSUE TITLE
Button Placement in Track and Thumbnail

### ISSUE THREAD

**Issue by Arnei** [opencast/opencast-editor#1157]
In the track selection view, the button is below the preview image.
In the thumbnail view, the buttons are to the right of the generated image (unless the screen width becomes relatively small)

![grafik](https://github.com/opencast/opencast-editor/assets/1752342/a361d04e-e9e5-4a53-8b32-84d6985c9ac4)
vs.
![grafik](https://github.com/opencast/opencast-editor/assets/1752342/876ccdc9-042b-4818-a72e-8ad45230b040)

This feels inconsistent. Olaf suggested in #1079 to uniformly have the buttons to the right, with a vertical alignment like in the thumbnail view.

**Comment by Arnei** [comment]
Seems like a good suggestion to me. I kinda somewhat feel like having a single button aligned below instead to the right would be more intuitive. But having the alignment (and style) be consistent across views should be more intuitive.

**Comment by oas777** [comment]
@lkiesow?
