### ISSUE TITLE
Fix alignment of workflow title

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast-editor#1178]
If the workflow selection is shown because there are more than one workflow tagged `editor` in Opencast, the workflow title is slightly misaligned with the radio button. A few pixels of top padding should fix that:

![Screenshot from 2023-10-02 21-24-32](https://github.com/opencast/opencast-editor/assets/1008395/3d4ff54b-314f-4cd4-9e20-70cb1197c5eb)

**Comment by joshijoe05** [comment]
Hello, I would like to work on this issue. Can you assign this to me?

**Comment by joshijoe05** [comment]
Can you guide me which file it actually was?

**Comment by Arnei** [comment]
Should be in `src/main/WorkflowSelection.tsx`

**Comment by Prashant04627** [comment]
Hi, Can i work on this issue. Is it still open?

**Comment by Arnei** [comment]
Hey, yes it is still open. I assigned you.

Please unassign yourself and/or let us know if you don't want to work on this after all, so that someone else can take this up.

**Comment by Prashant04627** [comment]
Lets do this!

**Comment by Prashant04627** [comment]
REACT_APP_GIT_SHA' is not recognized as an internal or external command,
operable program or batch file.
It says this when i started to run the project locally. Also i can't find the solution, Arnei can you help me out with this.

**Comment by Arnei** [comment]
That is strange o.O, haven't seen that one before.

Just to make sure the basics are covered: Command-line `git` and `npm` are set up on your device, and you ran `npm ci` (or somesuch) before running `npm start`?

**Comment by Prashant04627** [comment]
No nothing works. I think i should be unassigned. 
Thank you

**Comment by Arnei** [comment]
That is unfortunate, thank you very much for trying though.

**Comment by Dhananjay-12** [comment]
HI @Arnei , can I work on this ?

**Comment by Arnei** [comment]
You absolutely can @Dhananjay-12

**Comment by Dhananjay-12** [comment]
Hi, @Arnei  how to reach that workflow option. I only see these three for now.
![Screenshot from 2023-11-21 23-37-59](https://github.com/opencast/opencast-editor/assets/86868676/b89a6104-0386-4551-a5fc-92855b549818)

**Comment by Arnei** [comment]
Hi @Dhananjay-12,

On the screen you posted, click on the "Start processing" button to get to the workflow selection.
However, there will only be some text, because per default there is only one workflow. To get the radio menu to show up, you'll need at least to workflows. Now you could set up your own Opencast and configure it with multiple workflows for the editor, but it is probably way easier to temporarily hack some workflows into the frontend somehow. 
Btw the file you'll likely be looking at is `src/main/WorkflowSelection.tsx`

**Comment by Dhananjay-12** [comment]
Hi @Arnei, can you give me a hint on how to increase workflows , I could just come up with this dumb idea and it didn't work 
![Screenshot from 2023-11-22 23-30-03](https://github.com/opencast/opencast-editor/assets/86868676/822ad00f-b8de-443c-b94d-8eeeaeab3575)

**Comment by Arnei** [comment]
In `src/main/WorkflowSelection.tsx`:
```
  // Initialite redux states
  let workflows = useSelector(selectWorkflows)
  // Need to make copy to handle undefined displayOrder values
  workflows = [...workflows].sort((a, b) => {
    return (b.displayOrder - a.displayOrder)
  })
  workflows.push({id: "1324", name: "name", description: "description", displayOrder: 42})
  ```

**Comment by Dhananjay-12** [comment]
Hi @Arnei , is this good ?
![Screenshot from 2023-11-23 15-27-08](https://github.com/opencast/opencast-editor/assets/86868676/94a88234-419c-44f4-be9f-b6574a315099)

**Comment by Dhananjay-12** [comment]
Oops @Arnei , I think prettier made too many changes with the formatting, creating another PR
