### ISSUE TITLE
Shortcut help can't be opened

### ISSUE THREAD

**Issue by KatrinIhler** [opencast/opencast-editor#1188]
For the newest editor release running on the Bern test system, clicking on the shortcut help button at the top right corner doesn't do anything. There is no error message or anything, just nothing happens. Any ideas?

**Comment by Arnei** [comment]
Does it happen in all browsers?  
Does it also happen on editor.opencast.org, or only the new release shipped with Opencast?

**Comment by KatrinIhler** [comment]
After Sascha told me that it was working for him in the same browser (Firefox), I tested it again... and it works now. I'm very confused, because I could swear I've seen this multiple times, but I'm gonna take this as a win for now. Works on editor.opencast.org as well. Though it would be nice if a second click would make the shortcuts disappear again, I guess.

**Comment by Arnei** [comment]
Has not been cropping up again, so I'll consider this resolved.
