### ISSUE TITLE
Get rid of create-react-app

### ISSUE THREAD

**Issue by Arnei** [opencast/opencast-editor#1253]
This project uses Create-React-App. Create-React-App has been in-officially deprecated for quite some time now (the last release was over two years ago and active development has ceased since then). This will eventually lead to this project running into dependency versioning issues. For example, we're already running a typescript version unsupported by CRA.

In the interest of keeping this projects dependencies up-to-date, we should eventually get rid of CRA. This issue may serve as a discussion hub on how to best move forward.

**Comment by theumee** [comment]
Hey, can I work on this issue?

**Comment by Arnei** [comment]
Before we get to making changes, I think it would be best to hear opinions on how to proceed, particularly from the people more involved with the project. I myself am quite undecided on whether we should eject from CRA and manage bundling on our own (with webpack?), or if we should switch to a different framework (and which one? Vite? Next.js?). Or if it would be even better to keep CRA around for a bit longer, since it's not causing any real problems yet.

**Comment by theumee** [comment]
you are right, let's hear from them first.

**Comment by Arnei** [comment]
I think we should investigate switching to another framework. Since this has been a CRA project for quite some time now, I don't think many developers are interested in the additional control ejecting provides (also ejecting is likely gonna be pretty messy). And we rarely ever required that level of depedency control.

So my suggestion would be investigating a suitable candidate to switch to (Vite? Next.js?), and then do a "demo"-migration (low effort migration) to that to see how feasible a migration would be.
