### ISSUE TITLE
License field content displays inconsistently in editor vs metadata

### ISSUE THREAD

**Issue by Shinymonk** [opencast/opencast-editor#1377]
![MetadataShowsALLRIGHTS_WhileEditorFullText](https://github.com/opencast/opencast-editor/assets/4223485/157e3dfb-6027-4b5e-8a50-b3ff3e6514dd)

![ALLRIGHTS_WithMetadata](https://github.com/opencast/opencast-editor/assets/4223485/92665273-3c00-43c5-abf3-f39da1afc555)

**Comment by Shinymonk** [comment]
see also
https://github.com/opencast/opencast-admin-interface/issues/559

**Comment by Arnei** [comment]
It was determined that this is was an issue with the opencast-admin-interface, and the way the editor does this is in face correct. Therefore I'll close this.
