### ISSUE TITLE
Waveform in the editor should be there "instantly"/precalculated, takes more time than patience

### ISSUE THREAD

**Issue by Shinymonk** [opencast/opencast-editor#1379]
![WaveformGenerationWhenOpeningEditor](https://github.com/opencast/opencast-editor/assets/4223485/02e69f75-5f3c-417f-8ca2-a7c81c62c902)

**Comment by Shinymonk** [comment]
see also
https://github.com/opencast/opencast-admin-interface/issues/557

**Comment by Arnei** [comment]
Luckily this is already possible! You can have Opencast generate a waveform and send it to the editor, which will skip any generation attempts in the editor. More details in the ReadMe: https://github.com/opencast/opencast-editor?tab=readme-ov-file#notes-on-waveform-generation
