### ISSUE TITLE
Safari: Boxes around videos do not fit the videos

### ISSUE THREAD

**Issue by Arnei** [opencast/opencast-editor#1382]
In Safari, the boxes around the videos seem to always fill the screen, even if the videos themselves do not.

Tested with whatever Safari version is on MacOS 17.3 right now.

![grafik](https://github.com/opencast/opencast-editor/assets/14070005/34527137-7922-4838-ac75-835702a24912)

**Comment by ferishili** [comment]
I played around a bit, and came up with this finding:
The div with class `.css-1fsfa83` that has inline style of "width:unset;height:unset;" makes Safari confuse!
So try to set a calculated height for that div according to the aspect-ratio, could be considered as a workaround!
What do you think?
