### ISSUE TITLE
Editor “unusable” if event is being processed

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast-editor#171]
If an event is already being processed, there are no helpful messages in the editor. Users will just end up with an error when they try to start processing the event:

![Screenshot from 2021-02-03 17-02-22](https://user-images.githubusercontent.com/1008395/106774010-fb4d8100-6641-11eb-83cf-091630365b6f.png)

**Comment by lkiesow** [comment]
As discussed, we need at least a proper error explanation for what the “locked” error means

**Comment by Arnei** [comment]
There is now a (at least somewhat) helpful error message.

![Bildschirmfoto vom 2024-01-31 12-29-30](https://github.com/opencast/opencast-editor/assets/14070005/bd9e12ba-c98d-4f40-8806-b5602f13825c)
