### ISSUE TITLE
Processing duration

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast-editor#174]
It's nice to present feedback, but where does this processing time come from? It feels somewhat arbitrary:

![Screenshot from 2021-02-04 10-58-19](https://user-images.githubusercontent.com/1008395/106876512-0fdc5880-66d8-11eb-8787-f70b8bad4fb3.png)

**Comment by Arnei** [comment]
The projected processing time is extremely arbitrary actually, it's just `video duration * 2`. I can see how this could lead to more confusion than clarity, so I wouldn't mind removing it.
