### ISSUE TITLE
Metadata: Keys of the collection of the series are not unique

### ISSUE THREAD

**Issue by Arnei** [opencast/opencast-editor#215]
The collection of existing series from the `/editor/{mpId}/metadata.json` is of the form { { series-title, series-id}, {...} }. However, series titles are not suitable as keys, as they are not unique. Indeed, if there exist multiple series with the same title (for whatever reason) the endpoint will not deliver all of them.

**Comment by lkiesow** [comment]
Needs to be fixed in Opencst's list provider. Same issue exists in the admin interface.
