### ISSUE TITLE
Broken scrubber if there are no segments

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast-editor#253]
Testing on develop.opencast.org I found a broken editor:

![editor-broken-scrubber-no-segments](https://user-images.githubusercontent.com/1008395/114065852-63675000-989b-11eb-83e7-516c2bdfc3d6.png)

My guess is that the problem might be related to the event having no segments in which case I would expect the editor to assume a single segment for the recording.

**Comment by Arnei** [comment]
I've already taken a short a look at this, and your hunch goes in the right direction. The frontend will assume a single segment  in case there are none yet. However, it relies on the `duration` from the `edit.json` endpoint, which is null for this event, resulting in an erroneous state.
