### ISSUE TITLE
Editor delete segment

### ISSUE THREAD

**Issue by Melanie-Koller** [opencast/opencast-editor#361]
I like to have a small delete button for every segment. So it would be faster to delete segements.
![01](https://user-images.githubusercontent.com/57887263/121131367-f8e97680-c82f-11eb-87f8-b37113ef2bef.jpg)

**Comment by lkiesow** [comment]
I don't think that's a good idea. We want to keep the interface as simple as possible for normal people. Duplicating lots of buttons make it more confusing. Pro user can still use the key bindings to be faster.

**Comment by Arnei** [comment]
Closing this for now due to lack of discussion and agreement.
