### ISSUE TITLE
Meta-data Update without Cutting

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast-editor#39]
Users may end up misusing the editor for updating metadata which should work perfectly fine but may cause a lot of additional work on the server and will take quite a while since the video would actually be re-processed. Providing users with an additional “Update Metadata Only” in the finish step can greatly mitigate this problem while stil being simple enough for users to understand easily.

---

_Possibly after first sprint but may be easier to integrate directly_

**Comment by Arnei** [comment]
Does "Update Metadata Only" need to start a workflow (i.e. "Republish Metadata")? If not, it could maybe be part of the save button. (Referring to the general save button that is currently used to save changes from cutting)

**Comment by lkiesow** [comment]
Yes, it would need to start the workflow `republish-metadata`. But bringing up Save is a good point because republishing makes sense only if things are published already. Maybe we could even combine save and metadata update. That could be easier to understand for users:

- If the event has not been published yet
    - Save data to/Update data in the asset manager
- If the event has been published
    - Save data to/Update data in the asset manager
    - Run `republish-metadata` to update data on the publication

**Comment by Arnei** [comment]
Current workaround: Display the default workflow "Republish metadata" in the editor.

This issue may resolve itself if the Opencast project "Automatically republish metadata changes" ever gets implemented.
