### ISSUE TITLE
One request to save and start workflow

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast-editor#485]
Instead of having two REST calls for saving and starting a workflow, it would make sense to use a single one instead to ensure that the process is transactional, we don't send requests in an incorrect order and so that we need less requests overall. After all, you will never start a workflow without saving the data first, starting this on old data.

**Comment by Arnei** [comment]
Just to make this clear on a technical level: There's a seperate REST call for saving metadata specifically. Everything else (saving cut marks, thumbnails, starting a workflow etc.) is done in the other call. Still, as this issues suggests, those two calls should be one.
