### ISSUE TITLE
Create view to select subtitle track

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast-editor#582]
- Configuration to map Names to flavors. Example:
    - `Deutsch` → `subtitle/editor+de`
    - `Englisch` → `subtitle/editor+en`
    - …
- User sees all existing subtitles and can select them for editing
- User can add new subtitles
    - Only one subtitle per language configuration
- Idea: Tile view with existing subtitles and a “plus” tile

**Comment by Arnei** [comment]
* Alle Sprachen anzeigen, oder Add Subtitle Button?
		* Nur existierende Sachen anzeigen
	* Segmente nicht anzeigen

**Comment by Arnei** [comment]
> Only show buttons for existing subtitles

Can only reasonably implement this after #585 and #586 are done
