### ISSUE TITLE
opencast 12 status 400

### ISSUE THREAD

**Issue by luepschenk** [opencast/opencast-editor#743]
Hey.
I get an Error with the standalone editor in oc 12.0
Details: Status 400: Unable to load workflow. Event ID: XYZ

it is a litte strange. when I have multiple workflows in the editor. this error only occures with the first one in the List. If I change the workflows arround the error stays with the first one in the List. If I select any other workflow it procedes but the Variable {{duration}} is not filled in.
cheers kevin

**Comment by luepschenk** [comment]
Hey, thanks for the quick response.
If you start a workflow you get forwarded to a new page were it says the workflow is beeing applied and gives you an estimate on how long it may take. the estimate is (I guess) filled in with a variable and it is not filled in. (I use the german language therefore it says):

Änderungen erfolgreich in Opencast gespeichert. Die Verarbeitung Ihrer Änderungen kann bis zu {{duration}} Stunden dauern. Sie können nun den Editor schließen.

**Comment by Arnei** [comment]
The translation will be fixed with the next editor release, and since the main issue of this issue is fixed, 'll go ahead and close this.
