### ISSUE TITLE
German translation is questionable in parts

### ISSUE THREAD

**Issue by Arnei** [opencast/opencast-editor#765]
Some of the german translations are either weird or downright misleading
"Delete"
![Bildschirmfoto vom 2022-08-17 12-12-08](https://user-images.githubusercontent.com/14070005/185094146-f0b7a9f4-dfe4-49e9-8d34-68f2a39458af.png)
"Yes, save changes"
![Bildschirmfoto vom 2022-08-17 12-12-33](https://user-images.githubusercontent.com/14070005/185094185-b05881f0-75e5-4386-8253-d18ce45fb512.png)

**Comment by mliradelc** [comment]
Should this two be:

`Löschen`

and the second:

`Ja, Änderungen speichern` ?

**Comment by Arnei** [comment]
Those would work, yes.

**Comment by Arnei** [comment]
Another one: "Verarbeitet" should be "Verarbeiten".

**Comment by ziegenberg** [comment]
I updated some of the german translations in crowdin. Should be better now, if they get imported before the next release.

**Comment by ziegenberg** [comment]
The mentioned errors were fixed in:
- a7a08c01a6c188d1d5904aa2397b536ee91486fa
- 53777c277bb3ed765837eaf1d6809cdddad58a34
- 930cbe71e456fdc81e3a9bd9c882dbf6259a5c2b

So, in my opinion, this can be closed.
