### ISSUE TITLE
Language does not always load

### ISSUE THREAD

**Issue by mliradelc** [opencast/opencast-editor#766]
In the editor, the language library does not always load, showing the labels for translation instead.

Sometimes works well, sometimes not. It is very irregular, and it seems a timing issue. The dev console doesn't show any error.

If I enable the developer console, the language never loads (Even with the cache disabled)

Here is a video that shows the behavior:

https://user-images.githubusercontent.com/8040628/185371688-7b9ba31d-d27e-41e7-a5c7-32f4939a853a.mp4

**Comment by lkiesow** [comment]
I'm seeing the same thing from time to time. Hitting F5 helps, but that's certainly not great:

![Screenshot from 2022-10-12 15-36-52](https://user-images.githubusercontent.com/1008395/195357926-dcd772d0-6d84-47b3-94aa-b9b7047321a3.png)

What's interesting is, that things rendered a bit later will work (e.g. if you go to a new view)

![Screenshot from 2022-10-12 15-37-03](https://user-images.githubusercontent.com/1008395/195357895-9729564b-5afa-42f1-9c47-7648ad44c86a.png)

**Comment by dennis531** [comment]
So far, this bug didn't appear on my system and I can't reproduce it. Maybe the problem was caused by an erroneous package.
Does this issue still exist?

**Comment by Arnei** [comment]
Afaik it still exists, I think I've seen it fairly recently. But as Max said, it is terribly irregular, so it's hard to reproduce. And it might just be caused by an erroneous package, we don't know.

**Comment by dennis531** [comment]
I don't get this problem on Firefox, but on Chrome it appears.
