### ISSUE TITLE
Feature: Merge/combine/append videos

### ISSUE THREAD

**Issue by jondo** [opencast/opencast-editor#791]
I would like to add an intro/outro video to my records. For this a feature of combining two video seems necessary, so let me suggest this.

**Comment by Arnei** [comment]
As Greg suggested, themes seem to be a good alternative for your use case. Afaik the editor is more about removing parts from recordings than adding new parts to them, not sure how I would do that with the editor alone. Probably would have to run [Partial Import](https://docs.opencast.org/develop/admin/#workflowoperationhandlers/partial-import-woh/) after cutting or something like that.

**Comment by Arnei** [comment]
Closing this since op seems satisfied with the answers.
