### ISSUE TITLE
Inconsistent language flags

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast-editor#825]
Given the subtitle configuration
```toml
[subtitles.languages]
"captions/vtt+de" = "Deutsch"
"captions/vtt+en" = "English"
```
you end up with a view like this:

![Screenshot from 2022-10-13 16-14-23](https://user-images.githubusercontent.com/1008395/195628015-0fb78009-1947-45a9-bdc0-d40e930f2c95.png)

- Where does the German flag come from?
- Why is there none for English?
- Can we make this somewhat consistent?

**Comment by Arnei** [comment]
The code at fault is this function here: https://github.com/opencast/opencast-editor/blob/1a63c95efa6a41cadc09663612c918ab08f40672/src/main/SubtitleSelect.tsx#L66

> Where does the German flag come from?

It's unicode!

> Why is there none for English?

The function extracts a substring from the subflavor in the vague hope that it's a valid unicode flag. "en" is not a valid unicode flag.

> Can we make this somewhat consistent?

Probably not (without a lot of effort)! There's no standard way of telling which language a vtt file belongs to (or no language, or multiple languages...), so we would have to come up with one.

**Comment by lkiesow** [comment]
If it's only Unicode icons anyway, I've got an idea.
Why not let users configure them as well?
Something like this:

```toml
[subtitles.languages]
"captions/vtt+de" = "Deutsch"
"captions/vtt+en" = "English"

[subtitles.icons]
"captions/vtt+de" = "🇩🇪"
"captions/vtt+en" = "🇺🇸"
```

What do you think?

**Comment by Arnei** [comment]
Not a bad idea? I guess you can trust a person who sets up the config to set reasonable values for the icons.

**Comment by lkiesow** [comment]
Well… if we can't trust the admin, we have already lost anyway ;-P

**Comment by Arnei** [comment]
Although if we implement #826, your suggestion would not work for some subtitles, as we would then display subtitles that are not set in the config, right?

**Comment by lkiesow** [comment]
That's true. But that's true already, since those wouldn't necessary even have a `+lang` as part of the flavor. It's also more that I couldn't access a subtitle I knew was in the system and I wouldn't expect that to be common.
