### ISSUE TITLE
Show all existing subtitles

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast-editor#826]
If your media pacage has a subtitle which is found by the backend and delivered to the frontend, the frontend will still not show it unless you have specifically configured the flavor in `subtitles.languages`. This can easily cause existing subtitles to get lost.

It would be great if _all_ existing subtitles could be shown in the subtitle editor view. Though, I think, it's fine that only configured languafes are shown in the drop-down for creating new subtitle tracks.

**Comment by mtneug** [comment]
I'm unsure if I would agree. Writing workflows that can deal with subtitles in any language can be tricky. Our workflows only support specific languages. Showing non-configured languages in the editor could make people think that all subtitles are published. Not really a strong argument, so ultimately, I can live with any decision.

**Comment by mtneug** [comment]
Well, I'm ok with this change. My only concern was that if, e.g. subtitles for Dutch are in a mediapackage and thus editable with this change, our workflows (as in educast.nrw) currently are not flexible enough to publish them (as we only enlist specific languages), leaving the user wondering why they don't show up in the player. So I'm more leaning to hiding them in the editor as well. Again not a very strong argument ;)
