### ISSUE TITLE
Restart playback at the end

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast-editor#833]
If I'm right at the end of the video and hit playback again, it would be nice if we could actually restart playback from the start.

https://user-images.githubusercontent.com/1008395/196646830-ddf8a179-1786-4a61-958c-9f6f79354a8e.mp4

_(you want to enable audio if you watch that video)_

**Comment by RachitGarg-12** [comment]
@lkiesow i would like to contribute to this issue.

**Comment by lkiesow** [comment]
Thanks for taking this up.

**Comment by lkiesow** [comment]
Hi @RachitGarg-12, since Hacktoberfest is over and my guess is that you picked this up as part of it, do you still plan to work on this now that the event is over?
