### ISSUE TITLE
Wrong label for save button

### ISSUE THREAD

**Issue by fsufrre** [opencast/opencast-editor#839]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/84502288/196969971-6791cab1-f69e-4ca6-ba61-2114bc796634.png">

While editing you can save the current status without processing. It does save, but the button shows wrong label text.
It should say "Ja Änderungen speichern".

**Comment by Arnei** [comment]
Should be fixed in the new Opencast release (12.4) and since Editor release 2022-10-06 I believe. Please reopen if that is not the case.
