### ISSUE TITLE
Editor doesn't cut subtitles if video is cut

### ISSUE THREAD

**Issue by mliradelc** [opencast/opencast-editor#843]
Usability issue.

When a video has already subtitles or was subtitled completely, the editor should cut the subtitles in function the cut parameters.

In other words, if I edit the video should cut also the subtitles (generate a new ones for delivery and save the originals as a master).

![image](https://user-images.githubusercontent.com/8040628/197795322-253e4013-92f4-46b6-9e39-dfcd5d8cbbe3.png)

**Comment by lkiesow** [comment]
Subtitles are already cut in Opencast's editor backend. If you submit the subtitle from the screenshot and have it processed by the editor backend, you will get a correctly cut subtitle where the first segment has been shortened.

**Comment by mliradelc** [comment]
It didn't work for me. what workflow step should I add, because the video gets cut, but not the subtitles.

**Comment by Arnei** [comment]
Just your usual editor operation

```xml
    <operation
        id="editor"
        exception-handler-workflow="partial-error"
        description="Cutting the recording according to the edit decision list">
      <configurations>
        <configuration key="source-flavors">captions/vtt+en</configuration>
        <configuration key="smil-flavors">smil/tmp</configuration>
        <configuration key="target-smil-flavor">smil/tmp</configuration>
        <configuration key="target-flavor-subtype">vtt+en+trimmed</configuration>
        <configuration key="interactive">false</configuration>
      </configurations>
    </operation>
 ```

**Comment by mliradelc** [comment]
Thanks for the explanation, I thought that it was explicit, because if I can cut the video, should cut also the subtitles that the editor can read.
