### ISSUE TITLE
Language selector has poor contrast

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast-editor#859]
In dark mode, the language selector of the subtitle editor has a very poor contrast:

![Screenshot from 2022-10-28 16-58-00](https://user-images.githubusercontent.com/1008395/198674335-c36c3fd0-c9aa-40dd-8360-6680c26952ef.png)

**Comment by ziegenberg** [comment]
@lkiesow Your screenshot is from the test deployment of PR #841. On the current version editor.opencast.org it looks better:

![Screenshot from 2022-10-28 19-15-14](https://user-images.githubusercontent.com/856916/198695014-71f706e3-41a8-4a80-b475-d389480a3550.png)
