### ISSUE TITLE
The workflow “Test & Deploy” fails on pull requests created by dependabot

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast-editor#877]
Test & Deploy / Check organization membership completely fails on pull requests created by dependabot:

```
Run TheModdingInquisition/actions-team-membership@v1.0
Error: Error while trying to establish team membership: GraphqlResponseError: Request failed due to following response errors:
 - Could not resolve to a User with the login of 'dependabot[bot]'.
```

**Comment by lkiesow** [comment]
Maybe we should consider switching to [jamessingleton/is-organization-member](https://github.com/JamesSingleton/is-organization-member). That action shouldn't fail on bots and also doesn't require a personal access token.

**Comment by ziegenberg** [comment]
@lkiesow I decided against checking organization membership because:

> In order to check whether a member is part of the organization or not, the members must have their "Organization Visibility" set to Public.

If you look at https://github.com/orgs/opencast/people, only 9 out of 51 have it set to `Public`.
