### ISSUE TITLE
Change cc-icon to a more pictorial icon

### ISSUE THREAD

**Issue by cgruber-uos** [opencast/opencast-editor#897]
On the left side of the OC Editor UI you have a navigation bar with a cc-icon to create new and edit existing subtitles: 

![2022-11-15 10_12_48-Greenshot](https://user-images.githubusercontent.com/101632236/201878764-eb2f44ee-6c96-429d-bba5-6e12bd80c494.png)

The cc-icon is associated with "closed captioning" an english term that is not understandable e.g. for German users. The "Untertitel"-icon is also problematic, same issue as an "English" icon: not international understandable. So let us take a more abstract pictorial icon without any connotation to letters or languages: 

![2022-11-15 10_11_10-Greenshot](https://user-images.githubusercontent.com/101632236/201881209-1a32f911-ab07-468b-aa17-efa5f98a4ccf.png)

We shoould use an icon like this one:
https://escience-ew.blogs.uni-hamburg.de/untertitel-fuer-videos-erstellen/633/

Btw YouTube uses a similar one in the YT-player UI

![2022-11-15 10_26_28-Greenshot](https://user-images.githubusercontent.com/101632236/201882025-adcf990f-7a78-458a-9b9c-7201c7d651eb.png)

**Comment by cgruber-uos** [comment]
I took the current cc-inline-SVG from OC Editor's HTML source code and made a `*.svg`-file form it, deleted the "cc" and replaced it with the vectorized long and short dashes from https://mms.uni-hamburg.de/wp-content/uploads/2020/11/Subtiitrid_est-300x300-1.png so it's not perfect in case you zoom in but should work.

![subtitle-new](https://user-images.githubusercontent.com/101632236/202246342-6242713d-3196-49c5-827e-97ed2a6b9d02.svg)

**Comment by Arnei** [comment]
Alternative for getting a well-licensed subtitle icon: https://react-icons.github.io/react-icons/icons?name=fa

React-icons provides a subtitle icon from "Material Design Icons", and also includes fontawesome icons. Thus, we could replace our current fontawesome usage with react-icons.

**Comment by Arnei** [comment]
> I couldn't find any fitting icon in the react icon set. Did you see a similar icon as we have in mind? Is it possible to contribute a new icon to the set?

If you search for "subtitle" in the search bar on page i linked, it should come up with an icon called "MdOutlineSubtitles" which to me looks exactly like the Youtube icon.

> The license is no problem, the "Schöpfungshöhe" e.g. for the YT-icon is not high enough to violate any copyright.

That is good to know!

**Comment by cgruber-uos** [comment]
Yes great! So let's take the [MdOutlineSubtitles](https://react-icons.github.io/react-icons/search?q=subtitle). Not mirrowed is not that problem, in case using the React-icons makes it easier than a self generated!
