### ISSUE TITLE
Subtitle editor language chooser without flag

### ISSUE THREAD

**Issue by cgruber-uos** [opencast/opencast-editor#899]
After choosing the subtitle editor page in OC Studio you can choose a new or -- if existing -- already present language for the subtitle you like to edit. 

The "English flag"-icon is buggy atm and there is no flag displayed in the current version (left side): 

![2022-11-15 10_34_40-Greenshot](https://user-images.githubusercontent.com/101632236/201939348-d23b6396-e5fd-4ead-b7dd-e661f5e92f1e.png)

Other languages are working

![2022-11-15 10_35_10-Greenshot](https://user-images.githubusercontent.com/101632236/201939406-39671a73-302e-4f2d-986c-1b0f119ab5e3.png)

Nevertheless we should not just fixing the not showing up flag, but use language hints and descriptions without a flag indicator (e.g. "DE" "EN", right side first scrennshot in this comment) or just the writtten language without any flag / code because flags are not languages, see: 

https://www.flagsarenotlanguages.com/blog/best-practice-for-presenting-languages/

and **presents languages in their local name.**

**Comment by Arnei** [comment]
This is adressed by #860. Much like whether to present languages in their local name or not, this leaves the choice of which icons to use (or if any at all) to the administrator.

**Comment by cgruber-uos** [comment]
There is a missmatch in the language naming: 
- ok / Deutsch
- ok / English
- not-ok / Spanish

"Spanish" sholuld be "Español" as local name 


![2023-01-25 15_25_40-Opencast Editor – Mozilla Firefox](https://user-images.githubusercontent.com/101632236/214589609-3c14fbfe-8695-4c97-b577-570727e1c51d.png)

**Comment by Arnei** [comment]
> There is a missmatch in the language naming:
> 
>     * ok / Deutsch
> 
>     * ok / English
> 
>     * not-ok / Spanish
> 
> 
> "Spanish" sholuld be "Español" as local name
> 
> (or - not preferable, see above - change "Deutsch" to "German" for consistency)
> 
> ![2023-01-25 15_25_40-Opencast Editor – Mozilla Firefox](https://user-images.githubusercontent.com/101632236/214589609-3c14fbfe-8695-4c97-b577-570727e1c51d.png)

That is a different issue to the one described in the initial post, so I won't reopen this issue.
Also the described issue is a configuration thing (https://github.com/opencast/opencast-editor/blob/main/public/editor-settings.toml), so it shouldn't cause problems in production setups. Although I agree it would be nice to also make it consistent on `editor.opencast.org`-

**Comment by cgruber-uos** [comment]
> Also the described issue is a configuration thing (https://github.com/opencast/opencast-editor/blob/main/public/editor-settings.toml),

Btw. funny to see flags in source code! :-)
