### ISSUE TITLE
Waveform gets slightly brighter while button animation is in progress (in thumbnail step)

### ISSUE THREAD

**Issue by LukasKalbertodt** [opencast/opencast-editor#900]
https://user-images.githubusercontent.com/7419664/202409513-4333ffdb-2f4c-49a1-bfb7-809b037d71f0.mp4

No idea what could cause this. This happens to me in Chrome 107.0.5304.87. In Firefox it doesn't happen. I'm using editor.opencast.org (built from 8bf40b3b6b79569fe56240e3439e5a7c6676fce8). Happens with all buttons inside the thumbnail step, but not in any other step or with the main menu buttons.

**Comment by Arnei** [comment]
Does this still occur since the redesign?

**Comment by LukasKalbertodt** [comment]
Nope, can't reproduce it anymore. Probably because there are no buttons with growing animations anymore.
