### ISSUE TITLE
Additional Hotkey to play back video in the subtitle editor

### ISSUE THREAD

**Issue by Arnei** [opencast/opencast-editor#901]
Like in other views, the video in the subtitle editor can be played back by pressing `Space`. Unlike other views, the users focus will be inside of an input element most of the time, so pressing `Space` will create a whitespace character instead (as is expected and desired). Therefore, it would be nice to have an alternate hotkey for playing back the video that works while inside an input element. Maybe `Shift` + `Space`.

**Comment by dennis531** [comment]
I would suggest `Strg` + `Alt` + `Space` to be consistent with the other hotkeys.
