### ISSUE TITLE
Subtitle editor, make input fields better visible 

### ISSUE THREAD

**Issue by cgruber-uos** [opencast/opencast-editor#932]
Input fields for subtitle text and time marks are nicely formated in dark mode: Input fields have other background colors than the page background and a clear visible border: 

![2022-12-07 11_54_15-Greenshot](https://user-images.githubusercontent.com/101632236/206160819-3d20eff3-4333-43a6-9b57-7a7b38bdabc5.png)

We should make similar things with the "default" / white skin: 

![2022-12-07 11_54_14-Greenshot](https://user-images.githubusercontent.com/101632236/206160845-173e5131-23b9-49cb-889d-fb3218572d13.png)

Either making the input background light gray or the general background (then for all pages)!

**Comment by lkiesow** [comment]
I like the idea of having a slightly gray background and white input fields in light mode. If we make the input gray, they could be mistaken for deactivated fields.

**Comment by dennis531** [comment]
![image](https://user-images.githubusercontent.com/44410838/216040067-79b0eaa8-ddf0-468d-8ed6-c35e1f12caf2.png)

I set the background color to"whitesmoke" in light mode.
