### ISSUE TITLE
Random strings and wrong special characters in edited subtitle text

### ISSUE THREAD

**Issue by Piriya-VM** [opencast/opencast-editor#941]
We use Vosk to create subtitles and edit them in the subtitle editor.
After saving and publishing, the subtitle file includes strange strings and special character like ä, ü, ö don't get displayed correctly.
See the attached vtt file, screenshot and partial-publish Workflow.
```
WEBVTT

3lPSCXPUvSk3QfzzsrXDj
00:00.420 --> 00:05.930
Apfel

iOmyuq7YoRVkBdHrDHj8m
00:06.930 --> 00:10.530
Hallo ich bin Vosk und versuche nur 
zu Ueberleben irgendwas irgendwas.

3bW92IwxDIrqu0k_HdIeu
00:10.530 --> 00:14.100
orange

zPaQJaT9U0iBY2JI5sqFS
00:14.100 --> 00:18.750
kiwi 
irgendwas irgendwas irgendwas

lBh9Dx0GfstMMqgq-R1XG
00:19.920 --> 00:22.860
ananas
```

![editor_bug](https://user-images.githubusercontent.com/78363047/208886656-158387b7-bee2-4022-9827-49038f1daf93.png)

[partial-publish.txt](https://github.com/opencast/opencast-editor/files/10277064/partial-publish.txt)

**Comment by DZenker** [comment]
I can confirm this bug, this also happens in our installation (OC 12.6).

**Comment by fsufrre** [comment]
I can confirm this bug too. (OC 12.4)
Any ideas when this bug is fixed?

**Comment by Arnei** [comment]
Interestingly, I cannot confirm this bug (OC 0fb1c14, also newer versions). The characters `ä, ü, ö` render normally.

The "strange strings" like `3lPSCXPUvSk3QfzzsrXDj` are subtitle cue ids generated by vosk. I do not know why vosk generates them, but looking at the downloaded subtitle file they are perfectly legal WebVTT. Maybe Paella Player doesn't know how to handle them?

**Comment by fsufrre** [comment]
we are using amberscript. but i think the way of delivery is not the point. while saving the edited subtitle and republish the transcription, the *vtt file gets some extra strings. its visible in paella and also after downloading the *vtt File. I think the magic happens in "saving" process.

**Comment by Arnei** [comment]
True, it seems blaming the strage strings on vosk was hasty on my part.
